### ISSUE TITLE
Create App

### ISSUE THREAD

**Issue by aadshalshihry** [tagable/ar-sandbox#1]
Add the following components to app comp.

## Todo
- [x]  Create Nav
- [x]  Create Welcome wall
- [x]  Create news feed
- [x]  Create most read blog
- [x]  Create last update in editor
- [x]  Create Footer
 
![photo5091515160987805658](https://user-images.githubusercontent.com/10358496/34716846-16ec1000-f4ff-11e7-88b3-67b452d86b46.jpg)

**Comment by aadshalshihry** [comment]
Done 👍
