### ISSUE TITLE
Confirm your email

### ISSUE THREAD

**Issue by aadshalshihry** [tagable/ar-sandbox#10]
## Todo

- [x] add to the api
- [x] add it redux
- [x] show message if not confirm
- [x] send eamil to confirm

**Comment by aadshalshihry** [comment]
Done 👍
