### ISSUE TITLE
Create Singup & Signin page & style

### ISSUE THREAD

**Issue by aadshalshihry** [tagable/ar-sandbox#3]
##Todo

- [x] Create express app
- [x] Create Singin Comp.
- [x] Add styling to Singin comp.
- [x] add action & reducer
- [x] Add route point for signin in the api

**Comment by aadshalshihry** [comment]
Done
