### ISSUE TITLE
Create Blog

### ISSUE THREAD

**Issue by aadshalshihry** [tagable/ar-sandbox#6]
## Todo

- [ ] Create Model
- [ ] Create route
- [ ] Create relationship btn model

- [ ] Add route react
- [ ] Add action react
- [ ] Add reducer
- [ ] Do some styling
