### ISSUE TITLE
Create editor

### ISSUE THREAD

**Issue by aadshalshihry** [tagable/ar-sandbox#7]
## Todo

- [x] Create Model
- [x] Create relationship btn model
- [x] Add route react
- [x] Add action react
- [x] Add reducer
- [x] Create route (add, update)
- [x] Do some styling
- [x] coder-info get the token for the client
- [x] verfiy of the token is correct

**Comment by aadshalshihry** [comment]
Done 👍
